# Generated by Django 5.1.7 on 2025-04-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Controle_Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileForm',
        ),
    ]
