# Generated by Django 5.1.7 on 2025-04-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Controle_Financeiro', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
