# Generated by Django 5.1.7 on 2025-04-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Controle_Financeiro', '0010_alter_transacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APP_Controle_Financeiro.categoria'),
        ),
    ]
