# Generated by Django 5.1.7 on 2025-04-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Controle_Financeiro', '0011_alter_transacao_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='usuario',
            new_name='usuario_transacao',
        ),
    ]
